<?php

/**
 * Implementation of hook_install().
 */
function extlink_install() {
  // Weight needs to be 1 for compatibility with SpamSpan.
  db_query("UPDATE {system} SET weight = 1 WHERE name = 'extlink'");
}

/**
 * Implementation of hook_uninstall().
 */
function extlink_uninstall() {
  db_query("DELETE FROM {variable} WHERE name LIKE 'extlink_%'");
  cache()->deleteTags(array('variables' => TRUE));
}
