<?php
/**
 * @file
 * This is the file description for the AppCat Blocks module.
 *
 * This module defines custom blocks for the Applications Catalog.
 */

/**
 * Implements hook_menu_block_blocks().
 */
function appcat_blocks_menu_block_blocks() {
  // The array key is the block delta used by menu block.
  return array(
    'appcat_blocks-1' => array(
      'menu_name'   => 'navigation',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => 'Actions',
      'level'       => 1,
      'follow'      => 0,
      'depth'       => 0,
      'expanded'    => 1,
      'sort'        => 0,
    ),
  );
}
