<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_features_export_alter().
 *
 * Remove the uuid vocabulary terms, which we create in a separate
 * features module because the terms are used by multiple features
 * in this distro.
 * See http://drupal.org/node/1698290
 * (although it refers to tags rather than uuid_terms).
 */
function appcat_misc_features_export_alter(&$export, $module_name) {
  $content_definition_modules = array(
    'appcat_application_content',
    'appcat_organization_content',
  );
  if (in_array($module_name, $content_definition_modules) && isset($export['features']['taxonomy']) && isset($export['features']['uuid_term'])) {
    unset($export['features']['taxonomy']);
    unset($export['features']['uuid_term']);
  }
}
