<?php
/**
 * @file
 * Code for the OpenCivic Sponsor feature.
 */

include_once 'opencivic_sponsor.features.inc';

function opencivic_sponsor_populate_nodequeue() {
  $queue = nodequeue_load_queue_by_name('sponsors');
  $subqueues = nodequeue_load_subqueues_by_queue($queue->qid);
  $limit = $queue->size ? $queue->size : 10;
  foreach ($subqueues as $subqueue) {
    $nodes = db_select('node', 'n')
      ->condition('n.status', NODE_PUBLISHED)
      ->condition('n.type', $queue->types, 'IN')
      ->fields('n', array('nid'))
      ->range(0, $limit)
      ->execute()
      ->fetchAll();
    foreach ($nodes as $node) {
      nodequeue_subqueue_add($queue, $subqueue, $node->nid);
    }
  }
}
