<?php
/**
 * @file
 * Small module that defines green stars for the Fivestar ratings module.
 * By: 
 *   Sheldon Rampton
 */

/**
 * Implementation of hook_fivestar_widgets().
 *
 * This hook allows other modules to create additional custom widgets for
 * the fivestar module.
 *
 * @return array
 *   An array of key => value pairs suitable for inclusion as the #options in a
 *   select or radios form element. Each key must be the location of a css
 *   file for a fivestar widget. Each value should be the name of the widget.
 *
 * @see fivestar_fivestar_widgets()
 */
function fivestar_green_fivestar_widgets() {
  $path = drupal_get_path('module', 'fivestar_green');
  $widgets = array(
    $path . '/greenstar/greenstar.css' => 'Greenstars',
  );
  return $widgets;
}