language: php

php:
  - 5.3

mysql:
  database: opencivic_test
  username: root
  encoding: utf8

before_script:
  # navigate out of module directory to prevent blown stack by recursive module lookup
  # - cd ../..

  # Install drush from git clone
  - git clone --branch 6.x https://github.com/drush-ops/drush.git
  - export PATH="`pwd`/drush:$PATH"

  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

  # disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # create new site, stubbing sendmail path with true to prevent delivery errors and manually resolving drush path
  - mysql -e 'create database opencivic_test'
  # - drush --yes core-quick-drupal --profile=testing --no-server --db-url=mysql://root:@127.0.0.1/opencivic_test --enable=simpletest opencivic_test

