<?php
/**
 * @file
 * appcat_misc_default_content.features.node_export_features.inc
 */

/**
 * Implements hook_node_export_features_default().
 */
function appcat_misc_default_content_node_export_features_default() {
  $node_export = array(
  'code_string' => 'array(
  (object) array(
      \'vid\' => \'1\',
      \'uid\' => \'1\',
      \'title\' => \'Drupal\',
      \'log\' => \'\',
      \'status\' => \'1\',
      \'comment\' => \'1\',
      \'promote\' => \'0\',
      \'sticky\' => \'0\',
      \'vuuid\' => \'0c0ae929-f13d-af74-d5e6-331c218dbc8a\',
      \'nid\' => \'1\',
      \'type\' => \'application\',
      \'language\' => \'und\',
      \'created\' => \'1358140439\',
      \'changed\' => \'1358140439\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'uuid\' => \'1a4710f7-22ff-a854-3d8f-987e5eb075de\',
      \'revision_timestamp\' => \'1358140439\',
      \'revision_uid\' => \'1\',
      \'body\' => array(
        \'und\' => array(
          array(
            \'value\' => "<p><span style=\\"font-family: \'PT Sans\', \'Lucida Grande\', \'Lucida Sans Unicode\', sans-serif; line-height: 18px;\\">Drupal is a powerful content management system (CMS). CMSs enable easy management of workflow in a collaborative environment to power any type of website, from government sites to social networking sites. Although Drupal offers a sophisticated programming interface for developers, no programming skills are required for basic website installation and administration. Video: http://dai.ly/gabKRV For a full list of governments using drupal see: http://groups.drupal.org/node/24119#USA http://groups.drupal.org/government-sites#USA</span></p>",
            \'summary\' => \'\',
            \'format\' => \'filtered_html\',
            \'safe_value\' => " <p>Drupal is a powerful content management system (CMS). CMSs enable easy management of workflow in a collaborative environment to power any type of website, from government sites to social networking sites. Although Drupal offers a sophisticated programming interface for developers, no programming skills are required for basic website installation and administration. Video: <a href=\\"http://dai.ly/gabKRV\\">http://dai.ly/gabKRV</a> For a full list of governments using drupal see: <a href=\\"http://groups.drupal.org/node/24119#USA\\">http://groups.drupal.org/node/24119#USA</a> <a href=\\"http://groups.drupal.org/government-sites#USA\\">http://groups.drupal.org/government-sites#USA</a></p>\\n ",
            \'safe_summary\' => \'  \',
          ),
        ),
      ),
      \'field_image\' => array(
        \'und\' => array(
          array(
            \'fid\' => \'1\',
            \'alt\' => \'Drupal logo\',
            \'title\' => "Drupal\'s logo is called the \\"Druplicon.\\"",
            \'width\' => \'1180\',
            \'height\' => \'1350\',
            \'uid\' => \'1\',
            \'filename\' => \'druplicon.large_.png\',
            \'uri\' => \'public://content/applications/logos/druplicon.large_.png\',
            \'filemime\' => \'image/png\',
            \'filesize\' => \'25329\',
            \'status\' => \'1\',
            \'timestamp\' => \'1358140439\',
            \'type\' => \'image\',
            \'uuid\' => \'815cbf18-f5e7-c5b4-7122-2c09d5a091c8\',
            \'rdf_mapping\' => array(),
          ),
        ),
      ),
      \'field_aggregate_rating\' => array(),
      \'field_application_category\' => array(),
      \'field_application_sub_cate\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'27\',
          ),
          array(
            \'tid\' => \'1\',
          ),
        ),
      ),
      \'field_civic_category\' => array(),
      \'field_civic_sub_cate\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'98\',
          ),
        ),
      ),
      \'field_contributor\' => array(),
      \'field_creator\' => array(),
      \'field_deployment\' => array(),
      \'field_description\' => array(
        \'und\' => array(
          array(
            \'value\' => \'A content management system that powers various types of websites\',
            \'format\' => NULL,
            \'safe_value\' => \'A content management system that powers various types of websites\',
          ),
        ),
      ),
      \'field_download_url\' => array(
        \'und\' => array(
          array(
            \'url\' => \'http://drupal.org/project/drupal\',
            \'title\' => \'Download Drupal\',
            \'attributes\' => array(),
          ),
        ),
      ),
      \'field_feature_list\' => array(
        \'und\' => array(
          array(
            \'value\' => \'Excellent documentation and community with a highly active forum\',
            \'format\' => NULL,
            \'safe_value\' => \'Excellent documentation and community with a highly active forum\',
          ),
          array(
            \'value\' => \'Handles countless content types including video, text, blog, podcasts, and polls with robust user management, menu handling, real-time statistics and optional revision control\',
            \'format\' => NULL,
            \'safe_value\' => \'Handles countless content types including video, text, blog, podcasts, and polls with robust user management, menu handling, real-time statistics and optional revision control\',
          ),
          array(
            \'value\' => \'Focus on social publishing can help you create sites and applications to help your users express their opinions and engage with one another\',
            \'format\' => NULL,
            \'safe_value\' => \'Focus on social publishing can help you create sites and applications to help your users express their opinions and engage with one another\',
          ),
          array(
            \'value\' => \'Build internal and external-facing websites in a matter of hours, with no custom programming\',
            \'format\' => NULL,
            \'safe_value\' => \'Build internal and external-facing websites in a matter of hours, with no custom programming\',
          ),
          array(
            \'value\' => \'Lots of add-on modules to extend functionality\',
            \'format\' => NULL,
            \'safe_value\' => \'Lots of add-on modules to extend functionality\',
          ),
        ),
      ),
      \'field_install_url\' => array(
        \'und\' => array(
          array(
            \'url\' => \'http://www.websitedesigndrupal.com/\',
            \'title\' => \'Demo\',
            \'attributes\' => array(),
          ),
        ),
      ),
      \'field_keywords\' => array(),
      \'field_license\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'168\',
          ),
        ),
      ),
      \'field_related_applications\' => array(),
      \'field_release_notes\' => array(
        \'und\' => array(
          array(
            \'value\' => \'<p>The latest release version is Drupal 7.18.</p>\',
            \'format\' => \'filtered_html\',
            \'safe_value\' => " <p>The latest release version is Drupal 7.18.</p>\\n ",
          ),
        ),
      ),
      \'field_requirements\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'161\',
          ),
          array(
            \'tid\' => \'162\',
          ),
          array(
            \'tid\' => \'187\',
          ),
          array(
            \'tid\' => \'190\',
          ),
        ),
      ),
      \'field_screenshot\' => array(),
      \'field_software_type\' => array(
        \'und\' => array(
          array(
            \'tid\' => \'178\',
          ),
        ),
      ),
      \'field_url\' => array(
        \'und\' => array(
          array(
            \'url\' => \'http://drupal.org/\',
            \'title\' => NULL,
            \'attributes\' => array(),
          ),
        ),
      ),
      \'field_video\' => array(),
      \'rdf_mapping\' => array(
        \'rdftype\' => array(
          \'schema:SoftwareApplication\',
          \'sioc:Item\',
          \'foaf:Document\',
        ),
        \'title\' => array(
          \'predicates\' => array(
            \'schema:name\',
          ),
        ),
        \'created\' => array(
          \'predicates\' => array(
            \'dc:date\',
            \'dc:created\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'changed\' => array(
          \'predicates\' => array(
            \'dc:modified\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'body\' => array(
          \'predicates\' => array(
            \'schema:text\',
            \'content:encoded\',
          ),
        ),
        \'uid\' => array(
          \'predicates\' => array(
            \'sioc:has_creator\',
          ),
          \'type\' => \'rel\',
        ),
        \'name\' => array(
          \'predicates\' => array(
            \'schema:name\',
          ),
        ),
        \'comment_count\' => array(
          \'predicates\' => array(
            \'sioc:num_replies\',
          ),
          \'datatype\' => \'xsd:integer\',
        ),
        \'last_activity\' => array(
          \'predicates\' => array(
            \'sioc:last_activity_date\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'field_short_description\' => array(
          \'predicates\' => array(),
        ),
        \'url\' => array(
          \'predicates\' => array(
            \'schema:url\',
          ),
          \'type\' => \'rel\',
        ),
        \'field_homepage\' => array(
          \'predicates\' => array(),
        ),
        \'field_contributor\' => array(
          \'predicates\' => array(
            \'schema:contributor\',
          ),
          \'type\' => \'rel\',
        ),
        \'field_creator\' => array(
          \'predicates\' => array(
            \'schema:creator\',
          ),
          \'type\' => \'rel\',
        ),
        \'field_tags\' => array(
          \'predicates\' => array(
            \'schema:keywords\',
          ),
          \'type\' => \'rel\',
        ),
        \'field_logo\' => array(
          \'predicates\' => array(
            \'schema:thumbnailUrl\',
          ),
        ),
        \'field_videos\' => array(
          \'predicates\' => array(
            \'schema:video\',
          ),
        ),
        \'field_primary_function\' => array(
          \'predicates\' => array(
            \'schema:applicationCategory\',
          ),
          \'type\' => \'rel\',
        ),
        \'field_application_sub_category\' => array(
          \'predicates\' => array(
            \'schema:applicationSubCategory\',
          ),
        ),
        \'field_feature_list\' => array(
          \'predicates\' => array(
            \'schema:featureList\',
          ),
        ),
        \'field_releases\' => array(
          \'predicates\' => array(
            \'schema:releaseNotes\',
          ),
        ),
        \'field_software_requirements\' => array(
          \'predicates\' => array(
            \'schema:requirements\',
          ),
        ),
        \'field_screenshots\' => array(
          \'predicates\' => array(
            \'schema:screenshot\',
          ),
          \'type\' => \'rel\',
        ),
        \'field_additional_type\' => array(
          \'predicates\' => array(
            \'schema:additionalType\',
          ),
          \'type\' => \'rel\',
        ),
        \'field_image\' => array(
          \'predicates\' => array(
            \'schema:image\',
          ),
          \'type\' => \'rel\',
        ),
        \'field_accountable_person\' => array(
          \'predicates\' => array(
            \'schema:accountablePerson\',
          ),
          \'type\' => \'rel\',
        ),
        \'field_about\' => array(
          \'predicates\' => array(
            \'schema:about\',
          ),
          \'type\' => \'rel\',
        ),
        \'field_associated_media\' => array(
          \'predicates\' => array(
            \'schema:associatedMedia\',
          ),
          \'type\' => \'rel\',
        ),
        \'field_url\' => array(
          \'predicates\' => array(
            \'schema:url\',
          ),
        ),
        \'field_description\' => array(
          \'predicates\' => array(),
        ),
        \'field_alternative_headline\' => array(
          \'predicates\' => array(
            \'schema:alternativeHeadline\',
          ),
        ),
        \'field_aggregate_rating\' => array(
          \'predicates\' => array(
            \'schema:aggregateRating\',
          ),
        ),
        \'field_keywords\' => array(
          \'predicates\' => array(
            \'schema:keywords\',
          ),
          \'type\' => \'rel\',
        ),
        \'field_video\' => array(
          \'predicates\' => array(),
          \'type\' => \'rel\',
        ),
        \'field_application_category\' => array(
          \'predicates\' => array(
            \'schema:applicationCategory\',
          ),
          \'type\' => \'rel\',
        ),
        \'field_application_sub_cate\' => array(
          \'predicates\' => array(
            \'schema:applicationSubCategory\',
          ),
          \'type\' => \'rel\',
        ),
        \'field_download_url\' => array(
          \'predicates\' => array(
            \'schema:downloadUrl\',
          ),
        ),
        \'field_install_url\' => array(
          \'predicates\' => array(
            \'schema:installUrl\',
          ),
        ),
        \'field_release_notes\' => array(
          \'predicates\' => array(
            \'schema:releaseNotes\',
          ),
        ),
        \'field_requirements\' => array(
          \'predicates\' => array(
            \'schema:requirements\',
          ),
          \'type\' => \'rel\',
        ),
        \'field_screenshot\' => array(
          \'predicates\' => array(
            \'schema:screenshot\',
          ),
          \'type\' => \'rel\',
        ),
        \'field_civic_sub_cate\' => array(
          \'predicates\' => array(
            \'schema:applicationSubCategory\',
          ),
          \'type\' => \'rel\',
        ),
        \'field_civic_category\' => array(
          \'predicates\' => array(
            \'schema:applicationCategory\',
          ),
          \'type\' => \'rel\',
        ),
        \'field_related_applications\' => array(
          \'predicates\' => array(),
        ),
        \'field_license\' => array(
          \'predicates\' => array(),
          \'type\' => \'rel\',
        ),
        \'field_software_type\' => array(
          \'predicates\' => array(),
          \'type\' => \'rel\',
        ),
        \'field_deployment\' => array(
          \'predicates\' => array(),
        ),
      ),
      \'cid\' => \'0\',
      \'last_comment_timestamp\' => \'1358140439\',
      \'last_comment_name\' => NULL,
      \'last_comment_uid\' => \'1\',
      \'comment_count\' => \'0\',
      \'name\' => \'admin\',
      \'picture\' => \'0\',
      \'data\' => \'a:1:{s:7:"contact";i:1;}\',
      \'subscriptions_notify\' => TRUE,
      \'path\' => array(
        \'pid\' => \'208\',
        \'source\' => \'node/1\',
        \'alias\' => \'content/drupal\',
        \'language\' => \'und\',
      ),
      \'menu\' => NULL,
      \'node_export_drupal_version\' => \'7\',
      \'node_export_dependency\' => array(
        array(
          \'type\' => \'file\',
          \'id\' => \'1\',
          \'delta\' => 0,
          \'property\' => \'fid\',
          \'module\' => \'image\',
          \'field_name\' => \'field_image\',
          \'langcode\' => \'und\',
          \'uuid\' => \'815cbf18-f5e7-c5b4-7122-2c09d5a091c8\',
        ),
        array(
          \'type\' => \'taxonomy_term\',
          \'id\' => \'27\',
          \'delta\' => 0,
          \'property\' => \'tid\',
          \'module\' => \'taxonomy\',
          \'field_name\' => \'field_application_sub_cate\',
          \'langcode\' => \'und\',
          \'uuid\' => \'8cde29e4-d80c-d684-29a4-a05e177aa0e6\',
        ),
        array(
          \'type\' => \'taxonomy_term\',
          \'id\' => \'1\',
          \'delta\' => 1,
          \'property\' => \'tid\',
          \'module\' => \'taxonomy\',
          \'field_name\' => \'field_application_sub_cate\',
          \'langcode\' => \'und\',
          \'uuid\' => \'02025476-b0b6-4374-1152-2455d4550fc1\',
        ),
        array(
          \'type\' => \'taxonomy_term\',
          \'id\' => \'98\',
          \'delta\' => 0,
          \'property\' => \'tid\',
          \'module\' => \'taxonomy\',
          \'field_name\' => \'field_civic_sub_cate\',
          \'langcode\' => \'und\',
          \'uuid\' => \'89556980-b4d7-3234-519c-655245331f79\',
        ),
        array(
          \'type\' => \'taxonomy_term\',
          \'id\' => \'168\',
          \'delta\' => 0,
          \'property\' => \'tid\',
          \'module\' => \'taxonomy\',
          \'field_name\' => \'field_license\',
          \'langcode\' => \'und\',
          \'uuid\' => \'75ad63b9-cc0b-06a4-41a6-83de605c3c20\',
        ),
        array(
          \'type\' => \'taxonomy_term\',
          \'id\' => \'161\',
          \'delta\' => 0,
          \'property\' => \'tid\',
          \'module\' => \'taxonomy\',
          \'field_name\' => \'field_requirements\',
          \'langcode\' => \'und\',
          \'uuid\' => \'52a8c3a5-443b-3a84-f970-9c936222b636\',
        ),
        array(
          \'type\' => \'taxonomy_term\',
          \'id\' => \'162\',
          \'delta\' => 1,
          \'property\' => \'tid\',
          \'module\' => \'taxonomy\',
          \'field_name\' => \'field_requirements\',
          \'langcode\' => \'und\',
          \'uuid\' => \'5330ac54-d7c9-8944-69cc-4b08757afe7e\',
        ),
        array(
          \'type\' => \'taxonomy_term\',
          \'id\' => \'187\',
          \'delta\' => 2,
          \'property\' => \'tid\',
          \'module\' => \'taxonomy\',
          \'field_name\' => \'field_requirements\',
          \'langcode\' => \'und\',
          \'uuid\' => \'b4bdca4d-bbdd-eb34-8127-aecd910e789d\',
        ),
        array(
          \'type\' => \'taxonomy_term\',
          \'id\' => \'190\',
          \'delta\' => 3,
          \'property\' => \'tid\',
          \'module\' => \'taxonomy\',
          \'field_name\' => \'field_requirements\',
          \'langcode\' => \'und\',
          \'uuid\' => \'c425e455-708c-4084-456f-308ece4f3ee9\',
        ),
        array(
          \'type\' => \'taxonomy_term\',
          \'id\' => \'178\',
          \'delta\' => 0,
          \'property\' => \'tid\',
          \'module\' => \'taxonomy\',
          \'field_name\' => \'field_software_type\',
          \'langcode\' => \'und\',
          \'uuid\' => \'92d46be9-09bd-65f4-b1a4-310551bf066e\',
        ),
      ),
    ),
  (object) array(
      \'vid\' => \'2\',
      \'uid\' => \'1\',
      \'title\' => \'Welcome to the Apps Catalog\',
      \'log\' => \'\',
      \'status\' => \'1\',
      \'comment\' => \'1\',
      \'promote\' => \'0\',
      \'sticky\' => \'0\',
      \'vuuid\' => \'5659d509-20b1-7984-bdda-4920612a9cd6\',
      \'nid\' => \'2\',
      \'type\' => \'page\',
      \'language\' => \'und\',
      \'created\' => \'1358140692\',
      \'changed\' => \'1358140692\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'uuid\' => \'3cd9325e-7d04-dd14-3128-9fda2ffad50d\',
      \'revision_timestamp\' => \'1358140692\',
      \'revision_uid\' => \'1\',
      \'body\' => array(
        \'und\' => array(
          array(
            \'value\' => \'<p>Let&#39;s find out what&#39;s working, where.</p>\',
            \'summary\' => \'\',
            \'format\' => \'filtered_html\',
            \'safe_value\' => " <p>Let\'s find out what\'s working, where.</p>\\n ",
            \'safe_summary\' => \'  \',
          ),
        ),
      ),
      \'rdf_mapping\' => array(
        \'rdftype\' => array(
          \'foaf:Document\',
        ),
        \'title\' => array(
          \'predicates\' => array(
            \'dc:title\',
          ),
        ),
        \'created\' => array(
          \'predicates\' => array(
            \'dc:date\',
            \'dc:created\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'changed\' => array(
          \'predicates\' => array(
            \'dc:modified\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
        \'body\' => array(
          \'predicates\' => array(
            \'content:encoded\',
          ),
        ),
        \'uid\' => array(
          \'predicates\' => array(
            \'sioc:has_creator\',
          ),
          \'type\' => \'rel\',
        ),
        \'name\' => array(
          \'predicates\' => array(
            \'foaf:name\',
          ),
        ),
        \'comment_count\' => array(
          \'predicates\' => array(
            \'sioc:num_replies\',
          ),
          \'datatype\' => \'xsd:integer\',
        ),
        \'last_activity\' => array(
          \'predicates\' => array(
            \'sioc:last_activity_date\',
          ),
          \'datatype\' => \'xsd:dateTime\',
          \'callback\' => \'date_iso8601\',
        ),
      ),
      \'cid\' => \'0\',
      \'last_comment_timestamp\' => \'1358140692\',
      \'last_comment_name\' => NULL,
      \'last_comment_uid\' => \'1\',
      \'comment_count\' => \'0\',
      \'name\' => \'admin\',
      \'picture\' => \'0\',
      \'data\' => \'a:1:{s:7:"contact";i:1;}\',
      \'subscriptions_notify\' => TRUE,
      \'path\' => array(
        \'pid\' => \'209\',
        \'source\' => \'node/2\',
        \'alias\' => \'content/welcome-apps-catalog\',
        \'language\' => \'und\',
      ),
      \'menu\' => NULL,
      \'node_export_drupal_version\' => \'7\',
    ),
)',
);
  return $node_export;
}
