<?php
/**
 * @file
 * appcat_misc_taxonomy_app_terms.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function appcat_misc_taxonomy_app_terms_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Database',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '02025476-b0b6-4374-1152-2455d4550fc1',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Freedom of Information',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0237ec46-b21a-c4f4-7917-efcd3fd49cd3',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Administration',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '05fd52fc-a025-f4d4-1139-8ae021f7a79c',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Contact Relationship Management',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0adf46c5-5d7b-ba74-01a9-030bfaec9779',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Agriculture',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '11d77d10-d74f-4f54-0509-e1bfb831a64f',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Records & Archiving',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2be80a8b-1817-1f44-0965-8b25aab6a757',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Data aggregation',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '34cf95ee-3329-ef34-113f-10f7c556ddcb',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
  );
  $terms[] = array(
    'name' => 'Security and Confidentiality',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3834f82b-7027-ffc4-2984-44e32babfa64',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Games',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '3ef61d92-9025-59e4-71e8-14a426324365',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
  );
  $terms[] = array(
    'name' => 'Permits & Inspections',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '43c6071b-1569-4f04-3d74-a022a2412075',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Health',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4675178e-2422-7154-1ddb-57466b332f65',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Location',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '48cae313-9b1c-aa74-1d46-65289eb298d4',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Reporting',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '50928255-3962-5a34-cdc2-8f2892f7da7d',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Sewer',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '56a850d1-6bb0-ea04-0d76-511cb87b0c29',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Veterans',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5ef6283e-ad29-2a44-8dd0-5c2d8d07c9ea',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Elections',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '612f9f02-d125-b244-f57d-82fa0cc50de2',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Human Resource Management',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '635b0836-01c5-8bf4-4182-c50bf4482999',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Scheduling',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '63b4ab3b-f2e0-0b64-f550-d574fca05160',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Data Conversion',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '64416c32-f672-40d4-1988-26f550d62652',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'State',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '661a0d30-b43e-c7b4-b542-276ad1b635f5',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Data Integration',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6b9ef859-e2d8-1fd4-1162-1e611d376d53',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Crowdsourcing',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '774a8201-1536-b444-4118-09363f0cd12d',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(
      'und' => array(
        0 => array(
          'fid' => NULL,
          'alt' => '',
          'title' => '',
          'width' => '100',
          'height' => '100',
          'uid' => '1',
          'filename' => 'crowdsourcing.png',
          'uri' => 'public://application_category/icons/crowdsourcing.png',
          'filemime' => 'image/png',
          'filesize' => '4740',
          'status' => '1',
          'timestamp' => '1358649049',
          'type' => 'image',
          'uuid' => 'ada83812-d630-ceb4-05f9-7013844277b1',
          'rdf_mapping' => array(),
          'uuid_features_file_path' => 'profiles/apps_catalog/uuid_features_assets/crowdsourcing.png',
        ),
      ),
    ),
    'field_small_icon' => array(
      'und' => array(
        0 => array(
          'fid' => NULL,
          'alt' => '',
          'title' => '',
          'width' => '24',
          'height' => '24',
          'uid' => '1',
          'filename' => 'crowdsourcing-sm.png',
          'uri' => 'public://crowdsourcing-sm.png',
          'filemime' => 'image/png',
          'filesize' => '1981',
          'status' => '1',
          'timestamp' => '1358649730',
          'type' => 'image',
          'uuid' => '697a7988-1b6e-4364-6110-676fcab44acf',
          'rdf_mapping' => array(),
          'uuid_features_file_path' => 'profiles/apps_catalog/uuid_features_assets/crowdsourcing-sm.png',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Emergency Management',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7810a0ae-0c1d-80d4-e5b8-712728e5c835',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Content & Document Management',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7944ccc7-a714-2b94-3dfe-5f66307b658d',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Budget',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7d2c4b7f-4362-0a94-5508-15a534bf21b8',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Case Management',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7dde5486-b21f-3334-3938-82ad28cac72c',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Content Management System',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8cde29e4-d80c-d684-29a4-a05e177aa0e6',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Mobile',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '91dc0575-1800-4f14-419a-69f1cca0a5ee',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
  );
  $terms[] = array(
    'name' => 'Social Media',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'aa8541c9-80c8-8844-65f7-15846827b343',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Multilingual',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b3cab5de-e328-5e74-65f3-d21de66d779e',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Mapping',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => 'b49b12cc-efea-7614-91e5-632a860a549c',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
  );
  $terms[] = array(
    'name' => 'Mapping',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b500103f-e817-2954-c595-e216369e9fda',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Finance',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c17d8eb0-4780-90d4-dda9-baf45bdacf3e',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Consumer Protection',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c1fc0fe6-0ffa-8384-fdef-0760ee0297a6',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Research',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c388a07a-80d2-8a74-a1af-207323d59aac',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Statistics',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c7e35ae7-70f5-8124-3d02-2627700f8abd',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Geography',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ccda9890-e0ff-fc94-45bd-19110e69eba9',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Risk Management',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ce7455ec-de53-7494-6de3-4b1df28cc721',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Education',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd894dbac-04d0-b1b4-bd50-f8cdce18c73d',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Accessibility',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd8c5bc09-a03f-0c74-3933-50fd03f8d773',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Economic Development',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e99f6bbd-6138-2294-a920-2861a3e1f793',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Accounting',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ec36fc92-0d24-fa64-f953-87e45c937dd4',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Taxes',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'fd077659-2a00-7e54-81fd-81c04b780df6',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Policy',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'fe5c5302-ae39-7ec4-ed40-665bcdfbab3d',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  return $terms;
}
