<?php
/**
 * @file
 * appcat_misc_taxonomy_app_terms.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function appcat_misc_taxonomy_app_terms_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Accounting',
    'description' => NULL,
    'format' => NULL,
    'weight' => '1',
    'uuid' => '014d59f5-fd03-41ce-a060-3c5adab5127f',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Accounting',
          'format' => NULL,
          'safe_value' => 'Accounting',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => NULL,
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '1',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
    'parent' => array(
      0 => 'f7365ae9-b9c0-4978-87ad-89a04f2fdd17',
    ),
  );
  $terms[] = array(
    'name' => 'Case Management',
    'description' => NULL,
    'format' => NULL,
    'weight' => '4',
    'uuid' => '0687fef8-e7c9-441d-9b70-4d8714af0845',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Case Management',
          'format' => NULL,
          'safe_value' => 'Case Management',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => NULL,
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '2',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
    'parent' => array(
      0 => 'f7365ae9-b9c0-4978-87ad-89a04f2fdd17',
    ),
  );
  $terms[] = array(
    'name' => 'Scheduling',
    'description' => NULL,
    'format' => NULL,
    'weight' => '12',
    'uuid' => '1019dcf3-1147-4891-a15d-2fb655c61aa3',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Scheduling',
          'format' => NULL,
          'safe_value' => 'Scheduling',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => NULL,
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '3',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
    'parent' => array(
      0 => 'f7365ae9-b9c0-4978-87ad-89a04f2fdd17',
    ),
  );
  $terms[] = array(
    'name' => 'Administration',
    'description' => NULL,
    'format' => NULL,
    'weight' => '2',
    'uuid' => '1cd3b0bf-290c-4eff-a286-f84c2cf295e5',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Administration',
          'format' => NULL,
          'safe_value' => 'Administration',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => NULL,
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '4',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
    'parent' => array(
      0 => 'f7365ae9-b9c0-4978-87ad-89a04f2fdd17',
    ),
  );
  $terms[] = array(
    'name' => 'Data aggregation',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '5',
    'uuid' => '34cf95ee-3329-ef34-113f-10f7c556ddcb',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Data aggregation',
          'format' => NULL,
          'safe_value' => 'Data aggregation',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '  ',
          'safe_summary' => '',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '5',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Games',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '10',
    'uuid' => '3ef61d92-9025-59e4-71e8-14a426324365',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Games',
          'format' => NULL,
          'safe_value' => 'Games',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '  ',
          'safe_summary' => '',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '6',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Budget',
    'description' => NULL,
    'format' => NULL,
    'weight' => '3',
    'uuid' => '4d2252dd-974c-4978-b25e-7f62fe06cbb0',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Budget',
          'format' => NULL,
          'safe_value' => 'Budget',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => NULL,
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '7',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
    'parent' => array(
      0 => 'f7365ae9-b9c0-4978-87ad-89a04f2fdd17',
    ),
  );
  $terms[] = array(
    'name' => 'Statistics',
    'description' => NULL,
    'format' => NULL,
    'weight' => '3',
    'uuid' => '611a35a8-1dfc-4a18-9013-a182263e2184',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Statistics',
          'format' => NULL,
          'safe_value' => 'Statistics',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => NULL,
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '8',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
    'parent' => array(
      0 => '34cf95ee-3329-ef34-113f-10f7c556ddcb',
    ),
  );
  $terms[] = array(
    'name' => 'Security and Confidentiality',
    'description' => NULL,
    'format' => NULL,
    'weight' => '13',
    'uuid' => '668cbb72-d539-4248-96fe-a3cccb0854ea',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Security and Confidentiality',
          'format' => NULL,
          'safe_value' => 'Security and Confidentiality',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => NULL,
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '9',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
    'parent' => array(
      0 => 'f7365ae9-b9c0-4978-87ad-89a04f2fdd17',
    ),
  );
  $terms[] = array(
    'name' => 'Data Integration',
    'description' => NULL,
    'format' => NULL,
    'weight' => '1',
    'uuid' => '6c288527-43c7-4599-adc5-845c8c95271a',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Data Integration',
          'format' => NULL,
          'safe_value' => 'Data Integration',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => NULL,
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '10',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
    'parent' => array(
      0 => '34cf95ee-3329-ef34-113f-10f7c556ddcb',
    ),
  );
  $terms[] = array(
    'name' => 'Research',
    'description' => NULL,
    'format' => NULL,
    'weight' => '10',
    'uuid' => '74da3a8d-4c00-4b78-8263-97a084269a81',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Research',
          'format' => NULL,
          'safe_value' => 'Research',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => NULL,
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '11',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
    'parent' => array(
      0 => 'f7365ae9-b9c0-4978-87ad-89a04f2fdd17',
    ),
  );
  $terms[] = array(
    'name' => 'Crowdsourcing',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '3',
    'uuid' => '774a8201-1536-b444-4118-09363f0cd12d',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Crowdsourcing',
          'format' => NULL,
          'safe_value' => 'Crowdsourcing',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '  ',
          'safe_summary' => '',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '12',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Consumer Protection',
    'description' => NULL,
    'format' => NULL,
    'weight' => '5',
    'uuid' => '8bf07193-8652-4036-874b-5764c127d2bc',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Consumer Protection',
          'format' => NULL,
          'safe_value' => 'Consumer Protection',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => NULL,
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '13',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
    'parent' => array(
      0 => 'f7365ae9-b9c0-4978-87ad-89a04f2fdd17',
    ),
  );
  $terms[] = array(
    'name' => 'Mobile',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '15',
    'uuid' => '91dc0575-1800-4f14-419a-69f1cca0a5ee',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Mobile',
          'format' => NULL,
          'safe_value' => 'Mobile',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '  ',
          'safe_summary' => '',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '14',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Content & Document Management',
    'description' => NULL,
    'format' => NULL,
    'weight' => '6',
    'uuid' => '9c2d19bf-c61b-4e5f-b502-4ddccccee5d1',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Content & Document Management',
          'format' => NULL,
          'safe_value' => 'Content &amp; Document Management',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => NULL,
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '15',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
    'parent' => array(
      0 => 'f7365ae9-b9c0-4978-87ad-89a04f2fdd17',
    ),
  );
  $terms[] = array(
    'name' => 'Location',
    'description' => NULL,
    'format' => NULL,
    'weight' => '1',
    'uuid' => 'a2388b71-8135-4548-82ec-d41a8faf78d7',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Location',
          'format' => NULL,
          'safe_value' => 'Location',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => NULL,
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '16',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
    'parent' => array(
      0 => 'b49b12cc-efea-7614-91e5-632a860a549c',
    ),
  );
  $terms[] = array(
    'name' => 'Contact Relationship Management',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a2a7599e-c655-4e6e-b858-5a841fa6a0a4',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Contact Relationship Management',
          'format' => NULL,
          'safe_value' => 'Contact Relationship Management',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => NULL,
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '17',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
    'parent' => array(
      0 => 'fe72752c-86a7-4024-8e2f-45cc75d14502',
    ),
  );
  $terms[] = array(
    'name' => 'Database',
    'description' => NULL,
    'format' => NULL,
    'weight' => '2',
    'uuid' => 'a32aba42-1edc-40ef-9a46-154bd314b9e8',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Database',
          'format' => NULL,
          'safe_value' => 'Database',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => NULL,
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '18',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
    'parent' => array(
      0 => '34cf95ee-3329-ef34-113f-10f7c556ddcb',
    ),
  );
  $terms[] = array(
    'name' => 'Geography',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a5958a56-f7d0-4926-a770-a23d152b4d24',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Geography',
          'format' => NULL,
          'safe_value' => 'Geography',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => NULL,
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '19',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
    'parent' => array(
      0 => 'b49b12cc-efea-7614-91e5-632a860a549c',
    ),
  );
  $terms[] = array(
    'name' => 'Accessibility',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ace4c6be-0481-463f-b0b2-c00aad1933bb',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Accessibility',
          'format' => NULL,
          'safe_value' => 'Accessibility',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => NULL,
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '20',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
    'parent' => array(
      0 => 'f7365ae9-b9c0-4978-87ad-89a04f2fdd17',
    ),
  );
  $terms[] = array(
    'name' => 'Mapping',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '14',
    'uuid' => 'b49b12cc-efea-7614-91e5-632a860a549c',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Mapping',
          'format' => NULL,
          'safe_value' => 'Mapping',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '  ',
          'safe_summary' => '',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '21',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Data Conversion',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'bf9f2806-c657-4d22-8290-ffaf28a2f915',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Data Conversion',
          'format' => NULL,
          'safe_value' => 'Data Conversion',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => NULL,
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '22',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
    'parent' => array(
      0 => '34cf95ee-3329-ef34-113f-10f7c556ddcb',
    ),
  );
  $terms[] = array(
    'name' => 'Content Management System',
    'description' => NULL,
    'format' => NULL,
    'weight' => '7',
    'uuid' => 'cc058868-4787-43f9-b65f-40942c007a08',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Content Management System',
          'format' => NULL,
          'safe_value' => 'Content Management System',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => NULL,
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '23',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
    'parent' => array(
      0 => 'f7365ae9-b9c0-4978-87ad-89a04f2fdd17',
    ),
  );
  $terms[] = array(
    'name' => 'Human Resource Management',
    'description' => NULL,
    'format' => NULL,
    'weight' => '8',
    'uuid' => 'e32b83e9-4f9f-4de6-936a-bafaefa7e455',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Human Resource Management',
          'format' => NULL,
          'safe_value' => 'Human Resource Management',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => NULL,
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '24',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
    'parent' => array(
      0 => 'f7365ae9-b9c0-4978-87ad-89a04f2fdd17',
    ),
  );
  $terms[] = array(
    'name' => 'Reporting',
    'description' => NULL,
    'format' => NULL,
    'weight' => '9',
    'uuid' => 'ef4568b7-28cf-4175-bad9-38a82e6733b8',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Reporting',
          'format' => NULL,
          'safe_value' => 'Reporting',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => NULL,
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '25',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
    'parent' => array(
      0 => 'f7365ae9-b9c0-4978-87ad-89a04f2fdd17',
    ),
  );
  $terms[] = array(
    'name' => 'Misc',
    'description' => NULL,
    'format' => NULL,
    'weight' => '20',
    'uuid' => 'f7365ae9-b9c0-4978-87ad-89a04f2fdd17',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Misc',
          'format' => NULL,
          'safe_value' => 'Misc',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => NULL,
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '26',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Risk Management',
    'description' => NULL,
    'format' => NULL,
    'weight' => '11',
    'uuid' => 'fa1e4759-3c1d-4b1e-b972-1bd6adec506c',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Risk Management',
          'format' => NULL,
          'safe_value' => 'Risk Management',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => NULL,
          'summary' => NULL,
          'format' => NULL,
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '27',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
    'parent' => array(
      0 => 'f7365ae9-b9c0-4978-87ad-89a04f2fdd17',
    ),
  );
  $terms[] = array(
    'name' => 'Social',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '18',
    'uuid' => 'fe72752c-86a7-4024-8e2f-45cc75d14502',
    'vocabulary_machine_name' => 'application_category',
    'field_icon' => array(),
    'field_small_icon' => array(),
    'name_field' => array(
      'en' => array(
        0 => array(
          'value' => 'Social',
          'format' => NULL,
          'safe_value' => 'Social',
        ),
      ),
    ),
    'description_field' => array(
      'en' => array(
        0 => array(
          'value' => '',
          'summary' => NULL,
          'format' => 'filtered_html',
          'safe_value' => '  ',
          'safe_summary' => '',
        ),
      ),
    ),
    'translations' => array(
      'original' => 'en',
      'data' => array(
        'en' => array(
          'entity_type' => 'taxonomy_term',
          'entity_id' => '28',
          'language' => 'en',
          'source' => '',
          'uid' => '1',
          'status' => '1',
          'translate' => '0',
          'created' => '1365597600',
          'changed' => '1365597600',
        ),
      ),
    ),
  );
  return $terms;
}
