<?php
/**
 * @file
 * opencivic_core.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function opencivic_core_ctools_plugin_api($module = NULL, $api = NULL) {
  // if ($module == "cer" && $api == "default_cer_presets") {
  //   return array("version" => "1");
  // }
  // if ($module == "field_group" && $api == "field_group") {
  //   return array("version" => "1");
  // }
  // if ($module == "page_manager" && $api == "pages_default") {
  //   return array("version" => "1");
  // }
  // if ($module == "panelizer" && $api == "panelizer") {
  //   return array("version" => "1");
  // }
  // if ($module == "strongarm" && $api == "strongarm") {
  //   return array("version" => "1");
  // }
}

// /**
//  * Implements hook_views_api().
//  */
// function opencivic_organization_views_api() {
//   return array(
//     'api' => '3.0',
//   );
// }
