<?php
/**
 * @file
 * This is the file description for ocsetup module.
 *
 * In this more verbose, multi-line description, you can specify what this
 * file does exactly. Make sure to wrap your documentation in column 78 so
 * that the file can be displayed nicely in default-sized consoles.
 */

/**
 * Implements hook_menu().
 */
function ocsetup_menu() {
  $items = array();
  $items['ocsetup_home'] = array(
    'title' => 'Redirect',
    'page callback' => 'ocsetup_redirect',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['ocsetup'] = array(
    'title' => 'Set Up Open Civic',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ocsetup_form'),
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

function ocsetup_redirect() {
  drupal_goto('ocsetup');
}

function ocsetup_form() {
  if (!user_access('administer site configuration')) {
    drupal_goto('user');
  }
  else {
    // Set the title
    drupal_set_title(t('Prepare Site'));

    $form = array();

    $form['openingtext'] = array(
      '#markup' => '<h2>' . t('Please choose the components that you want to include in your OpenCivic website.') . '</h2>',
    );

    $form['actions'] = array(
     '#prefix' => '<div class="form-actions">',
     '#suffix' => '</div>',
    );
    $form['actions']['components'] = array(
     '#prefix' => '<div class="form-actions">',
     '#suffix' => '</div>',
    );
    $options = variable_get('ocset_options', ocsetup_options());
    $form['actions']['components'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Options'),
      '#description' => t('The description appears usually below the checkboxes.'),
      '#options' => $options,
      '#default_value' => array('ocmisc'),
    );

    $form['actions']['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Prepare your site',
    );

    return $form;
  }
}

function ocsetup_form_submit($form, &$form_state) {
  $options = variable_get('ocset_options', ocsetup_options());
  $components = array_filter($form_state['values']['components']);
  foreach ($components as $component) {
    switch ($component) {
      case 'ocmisc':
        features_install_modules(
          array(
            // 'appcat_misc_taxonomy_app_terms',
            // 'appcat_misc_taxonomy_civic_terms',
            'appcat_misc_taxonomy_terms',
            'appcat_misc_deltas',
            'appcat_misc',
            // 'appcat_misc_default_content',
            'appcat_misc_menus',
            'ocmisc_cat_man_do_settings',
          )
        );
        ocsetup_save_adaptivetheme();
        drupal_flush_all_caches();
        break;

      case 'appcat':
        features_install_modules(
          array(
            'opencivic_application',
            'opencivic_organization',
            'opencivic_deployment',
            'opencivic_story',
            // 'appcat_application_content',
            // 'appcat_application_contexts',
            // 'appcat_application_views',
            // 'appcat_organization_content',
            // 'appcat_organization_contexts',
            // 'appcat_organization_views',
            // 'appcat_deployment_node',
            // 'appcat_deployment_context',
            // 'appcat_deployment_views',
            // 'appcat_menus',
          )
        );
        ocsetup_aliases();
        drupal_flush_all_caches();
        break;

      case 'appcat_default_content':
        features_install_modules(
          array(
            'appcat_default_content',
          )
        );
        drupal_flush_all_caches();
        // Update path aliases for nodes.
        db_delete('url_alias')
          ->execute();
        $nids = db_select('node', 'n')
          ->fields('n')
          ->execute()
          ->fetchCol();
        pathauto_node_update_alias_multiple($nids, 'bulkupdate');
        // Resave deployment nodes to get the correct auto node titles.
        $nids = db_select('node', 'n')
          ->fields('n')
          ->condition('type', 'deployment','=')
          ->execute()
          ->fetchCol();
        $nodes = node_load_multiple($nids);
        foreach ($nodes as $node) {
          node_save($node);
        }
        cache_clear_all();
        break;

      case 'occomm':
        features_install_modules(
          array(
            'opencivic_blog',
            'opencivic_home',
            'opencivic_sponsor',
            // 'appcat_blog_node',
            // 'appcat_blog_views',
            // 'appcat_sponsor_node',
            // 'appcat_home_context',
            // 'appcat_home_views',
            // 'occomm_events',
            'appcat_search_db',
          )
        );
        drupal_flush_all_caches();
        // appcat_sponsor_node_populate_nodequeue();
        break;

      case 'occomm_default_content':
        features_install_modules(
          array(
            'appcat_blog_default_content',
          )
        );
        drupal_flush_all_caches();
        break;

      case 'ochack':
        features_install_modules(
          array(
            'ochack_problem',
            'ochack_project',
          )
        );
        drupal_flush_all_caches();
        break;

      case 'oclang':
        features_install_modules(
          array(
            'oclang_ui',
            'oclang_ui_contexts',
            'oclang_content',
          )
        );
        drupal_flush_all_caches();
        break;

      case 'ochack_default_content':
        break;

      case 'ocapi':
        features_install_modules(
          array(
            'ocapi',
            'ocapi_services',
          )
        );
        drupal_flush_all_caches();
        break;

      case 'ocodata':
        break;

      case 'occon':
        break;

      case 'ocdemo':
        break;

      case 'ocinvest':
        break;

      case 'ocdevel':
        features_install_modules(
          array(
            'appcat_devel',
          )
        );
        break;

      case 'ocfinish':
        variable_set('site_frontpage', 'frontpage');
        drupal_flush_all_caches();
        break;
    }
    unset($options[$component]);
  }
  $options = variable_set('ocset_options', $options);
}

function ocsetup_aliases() {
  // Define URL alias patterns.
  variable_set('pathauto_blog_pattern', 'blogs/[user:name]');
  variable_set('pathauto_forum_pattern', '[term:vocabulary]/[term:name]');
  variable_set('pathauto_node_application_pattern', 'app/[node:title]');
  variable_set('pathauto_node_article_pattern', 'article/[node:title]');
  variable_set('pathauto_node_blog_pattern', 'blog/[node:title]');
  variable_set('pathauto_node_deployment_pattern', 'deploy/[node:title]');
  variable_set('pathauto_node_organization_pattern', 'org/[node:title]');
  variable_set('pathauto_node_page_pattern', 'page/[node:title]');
  variable_set('pathauto_node_pattern', 'content/[node:title]');
  variable_set('pathauto_node_webform_pattern', 'form/[node:title]');
  variable_set('pathauto_punctuation_hyphen', 1);
  variable_set('pathauto_taxonomy_term_application_category_pattern', 'appcat/[term:name]');
  variable_set('pathauto_taxonomy_term_civic_category_pattern', 'civic/[term:name]');
  variable_set('pathauto_taxonomy_term_license_pattern', 'license/[term:name]');
  variable_set('pathauto_taxonomy_term_organization_type_pattern', 'orgype/[term:name]');
  variable_set('pathauto_taxonomy_term_pattern', '[term:vocabulary]/[term:name]');
  variable_set('pathauto_taxonomy_term_requirements_pattern', 'req/[term:name]');
  variable_set('pathauto_taxonomy_term_service_pattern', 'service/[term:name]');
  variable_set('pathauto_taxonomy_term_software_type_pattern', 'apptype/[term:name]');
  variable_set('pathauto_taxonomy_term_tags_pattern', 'tag/[term:name]');
  variable_set('pathauto_user_pattern', 'users/[user:name]');

  // Set node export configuration.
  variable_set('node_export_code', 'all');
  variable_set('node_export_dsv_delimiter', ',');
  variable_set('node_export_dsv_enclosure', '"');
  variable_set('node_export_dsv_escape_eol', 1);
  variable_set('node_export_dsv_seperator', '\\r\\n');
  variable_set('node_export_existing', 'revision');
  variable_set('node_export_filename', 'node-export[node_export_filename:nid-list]([node_export_filename:node-count]-nodes).[node_export_filename:timestamp].[node_export_filename:format]');
  variable_set('node_export_file_assets_path', 'profiles/opencivic/node_export_assets');
  variable_set('node_export_file_list', '10');
  variable_set('node_export_file_mode', 'inline');
  variable_set('node_export_file_supported_fields', 'file, image');
  variable_set('node_export_file_types', array(
    'application' => 'application',
    'blog' => 'blog',
    'deployment' => 'deployment',
    'organization' => 'organization',
    'sponsor' => 'sponsor',
    'article' => 0,
    'page' => 0,
    'webform' => 0,
  ));
  variable_set('node_export_format', array(
    'drupal' => 'drupal',
    'json' => 0,
    'serialize' => 0,
    'xml' => 0,
    'dsv' => 0,
  ));
  variable_set('node_export_reset_author_application', 1);
  variable_set('node_export_reset_author_article', 1);
  variable_set('node_export_reset_author_blog', 1);
  variable_set('node_export_reset_author_deployment', 1);
  variable_set('node_export_reset_author_organization', 1);
  variable_set('node_export_reset_author_page', 1);
  variable_set('node_export_reset_author_webform', 1);
  variable_set('node_export_reset_book_mlid_application', 0);
  variable_set('node_export_reset_book_mlid_article', 0);
  variable_set('node_export_reset_book_mlid_blog', 0);
  variable_set('node_export_reset_book_mlid_deployment', 0);
  variable_set('node_export_reset_book_mlid_organization', 0);
  variable_set('node_export_reset_book_mlid_page', 0);
  variable_set('node_export_reset_book_mlid_webform', 0);
  variable_set('node_export_reset_changed_application', 0);
  variable_set('node_export_reset_changed_article', 0);
  variable_set('node_export_reset_changed_blog', 0);
  variable_set('node_export_reset_changed_deployment', 0);
  variable_set('node_export_reset_changed_organization', 0);
  variable_set('node_export_reset_changed_page', 0);
  variable_set('node_export_reset_changed_webform', 0);
  variable_set('node_export_reset_created_application', 0);
  variable_set('node_export_reset_created_article', 0);
  variable_set('node_export_reset_created_blog', 0);
  variable_set('node_export_reset_created_deployment', 0);
  variable_set('node_export_reset_created_organization', 0);
  variable_set('node_export_reset_created_page', 0);
  variable_set('node_export_reset_created_webform', 0);
  variable_set('node_export_reset_last_comment_timestamp_application', 0);
  variable_set('node_export_reset_last_comment_timestamp_article', 0);
  variable_set('node_export_reset_last_comment_timestamp_blog', 0);
  variable_set('node_export_reset_last_comment_timestamp_deployment', 0);
  variable_set('node_export_reset_last_comment_timestamp_organization', 0);
  variable_set('node_export_reset_last_comment_timestamp_page', 0);
  variable_set('node_export_reset_last_comment_timestamp_webform', 0);
  variable_set('node_export_reset_menu_application', 0);
  variable_set('node_export_reset_menu_article', 0);
  variable_set('node_export_reset_menu_blog', 0);
  variable_set('node_export_reset_menu_deployment', 0);
  variable_set('node_export_reset_menu_organization', 0);
  variable_set('node_export_reset_menu_page', 0);
  variable_set('node_export_reset_menu_webform', 0);
  variable_set('node_export_reset_path_application', 0);
  variable_set('node_export_reset_path_article', 0);
  variable_set('node_export_reset_path_blog', 0);
  variable_set('node_export_reset_path_deployment', 0);
  variable_set('node_export_reset_path_organization', 0);
  variable_set('node_export_reset_path_page', 0);
  variable_set('node_export_reset_path_webform', 0);
  variable_set('node_export_reset_promote_application', 0);
  variable_set('node_export_reset_promote_article', 0);
  variable_set('node_export_reset_promote_blog', 0);
  variable_set('node_export_reset_promote_deployment', 0);
  variable_set('node_export_reset_promote_organization', 0);
  variable_set('node_export_reset_promote_page', 0);
  variable_set('node_export_reset_promote_webform', 0);
  variable_set('node_export_reset_revision_timestamp_application', 0);
  variable_set('node_export_reset_revision_timestamp_article', 0);
  variable_set('node_export_reset_revision_timestamp_blog', 0);
  variable_set('node_export_reset_revision_timestamp_deployment', 0);
  variable_set('node_export_reset_revision_timestamp_organization', 0);
  variable_set('node_export_reset_revision_timestamp_page', 0);
  variable_set('node_export_reset_revision_timestamp_webform', 0);
  variable_set('node_export_reset_status_application', 0);
  variable_set('node_export_reset_status_article', 0);
  variable_set('node_export_reset_status_blog', 0);
  variable_set('node_export_reset_status_deployment', 0);
  variable_set('node_export_reset_status_organization', 0);
  variable_set('node_export_reset_status_page', 0);
  variable_set('node_export_reset_status_webform', 0);
  variable_set('node_export_reset_sticky_application', 0);
  variable_set('node_export_reset_sticky_article', 0);
  variable_set('node_export_reset_sticky_blog', 0);
  variable_set('node_export_reset_sticky_deployment', 0);
  variable_set('node_export_reset_sticky_organization', 0);
  variable_set('node_export_reset_sticky_page', 0);
  variable_set('node_export_reset_sticky_webform', 0);

  // Define correspondint entity references.
  $records = array(
    array(
      'entity_types_content_fields' => 'node*application*field_related_applications*node*application*field_related_applications',
      'enabled' => 1,
    ),

    array(
      'entity_types_content_fields' => 'node*organization*field_member*node*organization*field_member',
      'enabled' => 0,
    ),
    array(
      'entity_types_content_fields' => 'node*organization*field_related_applications*node*application*field_contributor',
      'enabled' => 1,
    ),
    array(
      'entity_types_content_fields' => 'node*organization*field_related_applications*node*application*field_creator',
      'enabled' => 0,
    ),
  );
  foreach($records as $fields) {
    db_insert('cer')->fields($fields)->execute();
  }

}

function ocsetup_options() {
  return array(
    'ocmisc' => 'Miscellaneous startup stuff',
    'oclang' => 'Multilingual support',
    'appcat' => 'Applications Catalog',
    'appcat_default_content' => 'Applications Catalog default content',
    'occomm' => 'Community',
    'occomm_default_content' => 'Community default content',
    'ochack' => 'Hackathon',
    'ochack_default_content' => 'Hackathon default content',
    'ocapi' => 'API for Interoperability',
    'ocdevel' => 'Development features',
/*
    'ocodata' => 'Open Data (not yet available)',
    'occon' => 'Apps Contest (not yet available)',
    'ocdemo' => 'Civic Sandboxes (not yet available)',
    'ocinvest' => 'Investment Network (not yet available)',
// */
    'ocfinish' => 'Finish',
  );
}

function ocsetup_save_adaptivetheme() {
  watchdog('adaptive_theme_settings', 'starting', array('%error' => 'OK'), WATCHDOG_ERROR);
  form_load_include($form_state, 'inc', 'system', 'system.admin');
  $form_state = array(
    'build_info' => array(
      'args' => array('cat_man_do'),
    ),
    'values' => array (
      'var' => 'theme_cat_man_do_settings',
      'toggle_logo' => 1,
      'toggle_name' => NULL,
      'toggle_slogan' => NULL,
      'toggle_node_user_picture' => 1,
      'toggle_comment_user_picture' => 1,
      'toggle_comment_user_verification' => 1,
      'toggle_favicon' => 1,
      'toggle_main_menu' => NULL,
      'toggle_secondary_menu' => 1,
      'default_logo' => 1,
      'logo_path' => '',
      'logo_upload' => '',
      'default_favicon' => 1,
      'favicon_path' => '',
      'favicon_upload' => '',
      'bigscreen_layout' => 'three_col_grail',
      'bigscreen_sidebar_unit' => 'px',
      'bigscreen_sidebar_first' => '320',
      'bigscreen_sidebar_second' => '320',
      'bigscreen_page_unit' => 'px',
      'bigscreen_page_width' => '960',
      'bigscreen_set_max_width' => 1,
      'bigscreen_max_width_unit' => 'px',
      'bigscreen_max_width' => '960',
      'bigscreen_media_query' => 'only screen and (min-width:1025px)',
      'tablet_landscape_layout' => 'three_col_grail',
      'tablet_landscape_sidebar_unit' => '%',
      'tablet_landscape_sidebar_first' => '33',
      'tablet_landscape_sidebar_second' => '33',
      'tablet_landscape_page_unit' => '%',
      'tablet_landscape_page_width' => '100',
      'tablet_landscape_media_query' => 'only screen and (min-width:769px) and (max-width:1024px)',
      'tablet_portrait_layout' => 'one_col_stack',
      'tablet_portrait_sidebar_unit' => '%',
      'tablet_portrait_sidebar_first' => '50',
      'tablet_portrait_sidebar_second' => '50',
      'tablet_portrait_page_unit' => '%',
      'tablet_portrait_page_width' => '100',
      'tablet_portrait_media_query' => 'only screen and (min-width:420px) and (max-width:768px)',
      'smartphone_landscape_layout' => 'one_col_stack',
      'smartphone_landscape_sidebar_unit' => '%',
      'smartphone_landscape_sidebar_first' => '50',
      'smartphone_landscape_sidebar_second' => '50',
      'smartphone_landscape_media_query' => 'only screen and (min-width:361px) and (max-width:480px)',
      'smartphone_landscape_page_width' => '100',
      'smartphone_landscape_page_unit' => '%',
      'smartphone_portrait_media_query' => 'only screen and (max-width:360px)',
      'smartphone_portrait_page_width' => '100',
      'smartphone_portrait_page_unit' => '%',
      'smartphone_portrait_sidebar_first' => '100',
      'smartphone_portrait_sidebar_second' => '100',
      'smartphone_portrait_sidebar_unit' => '%',
      'smartphone_portrait_layout' => 'one_col_stack',
      'bigscreen_two_brick' => 'two-brick',
      'bigscreen_two_66_33' => 'two-66-33',
      'bigscreen_two_50' => 'two-50',
      'bigscreen_two_33_66' => 'two-33-66',
      'bigscreen_three_50_25_25' => 'three-50-25-25',
      'bigscreen_three_3x33' => 'three-3x33',
      'bigscreen_three_25_50_25' => 'three-25-50-25',
      'bigscreen_three_25_25_50' => 'three-25-25-50',
      'bigscreen_four_4x25' => 'four-4x25',
      'bigscreen_five_5x20' => 'five-5x20-2x3-grid',
      'bigscreen_six_6x16' => 'six-6x16-3x2-grid',
      'bigscreen_three_inset_right' => 'three-inset-right',
      'bigscreen_three_inset_left' => 'three-inset-left',
      'tablet_landscape_two_brick' => 'two-brick',
      'tablet_landscape_two_66_33' => 'two-66-33',
      'tablet_landscape_two_50' => 'two-50',
      'tablet_landscape_two_33_66' => 'two-33-66',
      'tablet_landscape_three_50_25_25' => 'three-50-25-25',
      'tablet_landscape_three_3x33' => 'three-3x33',
      'tablet_landscape_three_25_50_25' => 'three-25-50-25',
      'tablet_landscape_three_25_25_50' => 'three-25-25-50',
      'tablet_landscape_four_4x25' => 'four-4x25',
      'tablet_landscape_five_5x20' => 'five-5x20-2x3-grid',
      'tablet_landscape_six_6x16' => 'six-6x16-3x2-grid',
      'tablet_landscape_three_inset_right' => 'three-inset-right',
      'tablet_landscape_three_inset_left' => 'three-inset-left',
      'tablet_portrait_two_brick' => 'two-brick',
      'tablet_portrait_two_66_33' => 'two-66-33',
      'tablet_portrait_two_50' => 'two-50',
      'tablet_portrait_two_33_66' => 'two-33-66',
      'tablet_portrait_three_50_25_25' => 'three-50-25-25-stack-top',
      'tablet_portrait_three_3x33' => 'three-3x33-stack-top',
      'tablet_portrait_three_25_50_25' => 'three-25-50-25-stack-top',
      'tablet_portrait_three_25_25_50' => 'three-25-25-50-stack-top',
      'tablet_portrait_four_4x25' => 'four-4x25-2x2-grid',
      'tablet_portrait_five_5x20' => 'five-5x20-1x2x2-grid',
      'tablet_portrait_six_6x16' => 'six-6x16-2x3-grid',
      'tablet_portrait_three_inset_right' => 'three-inset-right-wrap',
      'tablet_portrait_three_inset_left' => 'three-inset-left-wrap',
      'smartphone_landscape_two_brick' => 'two-brick-stack',
      'smartphone_landscape_two_66_33' => 'two-66-33-stack',
      'smartphone_landscape_two_50' => 'two-50-stack',
      'smartphone_landscape_two_33_66' => 'two-33-66-stack',
      'smartphone_landscape_three_50_25_25' => 'three-50-25-25-stack',
      'smartphone_landscape_three_3x33' => 'three-3x33-stack',
      'smartphone_landscape_three_25_50_25' => 'three-25-50-25-stack',
      'smartphone_landscape_three_25_25_50' => 'three-25-25-50-stack',
      'smartphone_landscape_four_4x25' => 'four-4x25-stack',
      'smartphone_landscape_five_5x20' => 'five-5x20-stack',
      'smartphone_landscape_six_6x16' => 'six-6x16-stack',
      'smartphone_landscape_three_inset_right' => 'three-inset-right-stack',
      'smartphone_landscape_three_inset_left' => 'three-inset-left-stack',
      'enable_custom_media_queries' => 1,
      'global_default_layout_toggle' => NULL,
      'global_default_layout' => 'smartphone-portrait',
      'global_files_path' => 'public_files',
      'custom_files_path' => '',
      'disable_responsive_styles' => NULL,
      'load_html5js' => 1,
      'load_onmediaqueryjs' => NULL,
      'load_ltie8css' => NULL,
      'load_respondjs' => NULL,
      'load_scalefixjs' => NULL,
      'adaptivetheme_meta_viewport' => 'width=device-width, initial-scale=1',
      'adaptivetheme_meta_mobileoptimized' => 'width',
      'adaptivetheme_meta_handheldfriendly' => 'true',
      'adaptivetheme_meta_apple_mobile_web_app_capable' => 'yes',
      'chrome_edge' => NULL,
      'clear_type' => NULL,
      'expose_regions' => NULL,
      'show_window_size' => NULL,
      'atcore_version_test' => NULL,
      'load_all_panels' => NULL,
      'load_all_panels_no_sidebars' => 0,
      'enable_extensions' => NULL,
      'enable_font_settings' => 0,
      'enable_heading_settings' => 0,
      'enable_image_settings' => 0,
      'enable_apple_touch_icons' => 0,
      'enable_exclude_css' => 0,
      'enable_custom_css' => 0,
      'enable_context_regions' => 0,
      'enable_float_region_blocks' => 0,
      'enable_markup_overides' => 0,
      'at-settings__active_tab' => 'edit-bigscreen',
      'at_core' => '7.x-3.x',
      'submit' => 'Save configuration',
      'form_build_id' => 'form-eo2jH_FNXinkJBMPLw9aRH7dtYJWsJeZaiU15efigoI',
      'form_token' => 'rXO7lRvwkzcuiTwj7XmL0qZTMb09buPapHMeDR0QTpA',
      'form_id' => 'system_theme_settings',
      'op' => 'Save configuration',
    ),
  );
  drupal_form_submit('system_theme_settings', $form_state);
  $errors = form_get_errors();
  if (!empty($errors)) {
    foreach ($errors as $error) {
      $msg = 'Error: %error';
      $var = array('%error' => $error);
      watchdog('adaptive_theme_settings', $msg, $var, WATCHDOG_ERROR);
    }
  }
}
