<?php
/**
 * @file
 * appcat_misc_taxonomies.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function appcat_misc_taxonomies_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'eMarketplace',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '00c31218-33c1-d894-b980-7067527aa4b2',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'National',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '1',
    'uuid' => '015ef97b-ae73-ec04-5536-cd54a0e3302b',
    'vocabulary_machine_name' => 'organization_type',
  );
  $terms[] = array(
    'name' => 'Database',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '02025476-b0b6-4374-1152-2455d4550fc1',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Freedom of Information',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0237ec46-b21a-c4f4-7917-efcd3fd49cd3',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Apache',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '05b1c7a4-0023-3594-b95b-0c9d7c4468c1',
    'vocabulary_machine_name' => 'license',
  );
  $terms[] = array(
    'name' => 'Administration',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '05fd52fc-a025-f4d4-1139-8ae021f7a79c',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Proprietary',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '083e978f-3195-af64-b564-89b95abeaf2d',
    'vocabulary_machine_name' => 'license',
  );
  $terms[] = array(
    'name' => 'File Sharing',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '08b57fec-c3d3-d124-c9cb-27566146d336',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Contact Relationship Management',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0adf46c5-5d7b-ba74-01a9-030bfaec9779',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Microsoft SQL Server',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0b795a21-3080-e124-099a-2ddd3d0bd0d1',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'ArcGIS for Server',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0d1acccf-dd8d-d454-f516-1cb7cc80fcc2',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Legislation & Governance',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0e076f86-d52a-1fc4-8973-996c6b976a9d',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Idea Sourcing',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '10c848aa-9525-4c64-bd77-c9826426589a',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Positive Influence',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '10f7d437-a1d4-bac4-45a5-a7e55e84ce09',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Interactive Surface',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '117ed73d-65c2-65a4-b1a0-814fea683e9f',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Agriculture',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '11d77d10-d74f-4f54-0509-e1bfb831a64f',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Electronic Mailing List',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1232602a-29a1-85e4-993c-2cf7e57a9482',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Collaborative Editing',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '136d0a8a-a266-3064-299a-bc59287ce7f1',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Webinar',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '141c67d7-6d8e-dea4-d93b-124f6bfe910d',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Brigade',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '146fe6a3-19c8-db64-e948-ce2621a3dd50',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Serious Games',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '156ea517-e542-afc4-e104-9d36b4fa3611',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Time Banking',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '185af492-08e8-e994-7dc1-d9c5223ad760',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Ranking',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '18af7668-09bd-f994-e9a6-55128bcff0c9',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Software development',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '1abe8b55-02a9-5864-6935-5fc4544b3bd0',
    'vocabulary_machine_name' => 'service',
  );
  $terms[] = array(
    'name' => 'Veterans Services',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1c143631-1e6c-df44-cddd-827fa8b3f1d3',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'GoogleMaps',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1fdd6053-1c96-23d4-b1d0-0da6a8ead2ee',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Scheduling',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '20edd0fe-006a-6134-e953-d3c337e02c88',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Parks & Recreation',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '228819c8-cd7b-15d4-5579-b9bda198e0a7',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Sanitation & Recycling',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '22a19f8c-74c6-0274-65e9-de2f991c360d',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Interactive Voice Response (IVR)',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '22e30d7e-8d6d-f6c4-3931-b6bfb862ae50',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Online Consultation',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '25f06d32-54db-12a4-91f5-8b40dde047fe',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Linux',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '26642fe1-5a91-d2f4-dd5d-d99e3e0248ab',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'iPhone',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '289f2033-272a-8e24-d1ac-167e0e1db120',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Transportation',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '290f7030-9810-5b74-0971-8653b3ff985b',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Interactive TV',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2acc68ed-615b-6894-edb5-767150637201',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'REST',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2b9aafe8-52ff-2404-2964-60466a27d3c8',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Records & Archiving',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2be80a8b-1817-1f44-0965-8b25aab6a757',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Online Prediction Markets',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2c89cb14-699f-0c64-5144-ff87839e5625',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Public Safety & Emergency Management',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2fe6af03-1bee-b004-39e9-858bb4f5fe36',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'eSatisfaction',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3170ed1f-6cb0-e1e4-457b-866ea58c8b42',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Data aggregation',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '34cf95ee-3329-ef34-113f-10f7c556ddcb',
    'vocabulary_machine_name' => 'application_category',
  );
  $terms[] = array(
    'name' => 'GeoServer',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3507ed07-6f16-9024-8957-24397d654009',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'jQuery',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '35189430-ffb6-7644-41b8-41cf32ab5639',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Electronic Poll',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '35ec6896-dfa1-afa4-41b6-1282d1398681',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Natural Resources & Environment',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '361eca87-3556-4594-891d-6faa1354dac4',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Digital Dashboards',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3785566a-183a-5564-b9d7-0787588584e0',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Security and Confidentiality',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3834f82b-7027-ffc4-2984-44e32babfa64',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Virtual Meetings',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '38c84f8e-327b-35a4-d110-9516062b04de',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'OpenLayers',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '38ea2767-2227-92c4-d19c-3c70bd984f3b',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Android',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '395f8927-4312-5d44-fd53-912fe944ca4e',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'MS Office',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3e13c3fc-df7a-42b4-319e-e4bdc97c632d',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Games',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '3ef61d92-9025-59e4-71e8-14a426324365',
    'vocabulary_machine_name' => 'application_category',
  );
  $terms[] = array(
    'name' => 'Person',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '8',
    'uuid' => '413eeea4-79c9-a6f4-2543-51e86146dcba',
    'vocabulary_machine_name' => 'organization_type',
  );
  $terms[] = array(
    'name' => 'Enhanced Transparency',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4171f731-6d1d-ee74-d559-0bf5f284304c',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Citizen Services & 311',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '42f05f6f-21f1-8ae4-e5d6-fcc3b4757ef3',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Permits & Inspections',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '43c6071b-1569-4f04-3d74-a022a2412075',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Commodity Exchange',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '44aef33b-26fc-1094-e5f9-d27afde193ae',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Education',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '45d91cf3-3e47-4034-b5f3-06a42fa0c977',
    'vocabulary_machine_name' => 'civic_category',
  );
  $terms[] = array(
    'name' => 'Health',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4675178e-2422-7154-1ddb-57466b332f65',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Budget & Finance',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4802ea15-d187-d544-7975-4b5536019c4a',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Location',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '48cae313-9b1c-aa74-1d46-65289eb298d4',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Electronic Citizen Jury',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4900d255-fc9c-e264-f501-f7ec937fa1c3',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'NOSA',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '490ec9d9-995d-9124-3d6c-9c448d923c62',
    'vocabulary_machine_name' => 'license',
  );
  $terms[] = array(
    'name' => 'Virtual Environments',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4acce4d5-de6f-d6a4-796f-f95c04da4c66',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Government',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '9',
    'uuid' => '4c079e6a-9a63-e3c4-1d82-58faf61c70c2',
    'vocabulary_machine_name' => 'organization_type',
  );
  $terms[] = array(
    'name' => 'Django',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4d2e47a6-0d0b-06a4-7520-fe07325c7779',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Binary',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '4dec34a2-080c-1a04-6981-bbcf58708af1',
    'vocabulary_machine_name' => 'software_type',
  );
  $terms[] = array(
    'name' => 'Reporting',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '50928255-3962-5a34-cdc2-8f2892f7da7d',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Simulations',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '519493e4-d73d-5314-e9b4-c7f493799750',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'iOS',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5206408c-3558-1424-9db1-7493d0731d6d',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Apache',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '52a8c3a5-443b-3a84-f970-9c936222b636',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'PHP',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5330ac54-d7c9-8944-69cc-4b08757afe7e',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Sewer',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '56a850d1-6bb0-ea04-0d76-511cb87b0c29',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'ColdFusion',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '59056455-ec7d-a074-6517-09f3738aacff',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Informed Investment Networks',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5997a4a1-51fe-eaa4-396b-0455040748bb',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Regional',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '2',
    'uuid' => '59cf3fec-0a4b-5de4-e581-e0b80fe62b54',
    'vocabulary_machine_name' => 'organization_type',
  );
  $terms[] = array(
    'name' => 'Status Updates',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5b5f0270-7f00-7a54-9df3-734a6499d956',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Nonprofit/Foundation/NGO',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '7',
    'uuid' => '5bdb8fa8-4f14-acb4-d9e3-363648a7ba83',
    'vocabulary_machine_name' => 'organization_type',
  );
  $terms[] = array(
    'name' => 'Veterans',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5ef6283e-ad29-2a44-8dd0-5c2d8d07c9ea',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Video Views',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5fccf249-cbc9-4424-7131-e8386fe34e67',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'State',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '3',
    'uuid' => '60ee3e65-7fc0-7524-cd44-e2d579c637c8',
    'vocabulary_machine_name' => 'organization_type',
  );
  $terms[] = array(
    'name' => 'Javascript',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6124e48d-1259-3834-999a-256e1d3c9240',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Elections',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '612f9f02-d125-b244-f57d-82fa0cc50de2',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Blogging',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6267bd04-4d11-4d84-bd55-39ebb4f1eb13',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Content Hosting',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '631c6601-62e8-9b24-7dc1-1bf550721782',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Human Resource Management',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '635b0836-01c5-8bf4-4182-c50bf4482999',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Scheduling',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '63b4ab3b-f2e0-0b64-f550-d574fca05160',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Data Conversion',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '64416c32-f672-40d4-1988-26f550d62652',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'State',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '661a0d30-b43e-c7b4-b542-276ad1b635f5',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Proximity Networking',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '67ddc84b-181e-ba44-cdf0-e90d74242c85',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Revenue & Taxes',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6867e7c0-3810-2564-f166-9bf32460c316',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Online Memo',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '68da7229-fcaa-cc54-c995-6725ad1a57a6',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Online Pledges',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '69598580-143b-7134-1529-5a88149e2b0e',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Data Integration',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6b9ef859-e2d8-1fd4-1162-1e611d376d53',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Public Works & Utilities',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '700bff9f-a8a8-75f4-fdb4-fd0145b90613',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Recommendation Systems',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '70150dc0-b70e-f9a4-ad69-db54060dd6dd',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'GPL',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '75ad63b9-cc0b-06a4-41a6-83de605c3c20',
    'vocabulary_machine_name' => 'license',
  );
  $terms[] = array(
    'name' => 'Crowdsourcing',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '774a8201-1536-b444-4118-09363f0cd12d',
    'vocabulary_machine_name' => 'application_category',
  );
  $terms[] = array(
    'name' => 'Emergency Management',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7810a0ae-0c1d-80d4-e5b8-712728e5c835',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Online Quizzes',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '78719f45-016e-f824-6906-1bcb0ed0b930',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Content & Document Management',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7944ccc7-a714-2b94-3dfe-5f66307b658d',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'SaaS / Hosted',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '7a086454-1af3-ae24-c9b4-3d36b0aab41f',
    'vocabulary_machine_name' => 'software_type',
  );
  $terms[] = array(
    'name' => 'Arts & Culture',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7a5b3e98-ca91-6744-39e0-036228259007',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'OSX',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7bb84698-9358-d4c4-3d89-d787c2ce2ed8',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Ratings',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7c60ae02-9e65-0334-4dd2-43be9f1cec1f',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Budget',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7d2c4b7f-4362-0a94-5508-15a534bf21b8',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Case Management',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7dde5486-b21f-3334-3938-82ad28cac72c',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Opinion Sourcing',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7e8220c1-d893-b654-95e7-1f6b2e65abda',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Zend Framework',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '80e4c446-bfb4-5e84-959f-fe00e7329626',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'County',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '4',
    'uuid' => '814f8fa1-bc57-8cd4-a585-590e50c675b6',
    'vocabulary_machine_name' => 'organization_type',
  );
  $terms[] = array(
    'name' => '.NET framework',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '82141464-508c-d104-a9df-612b8d2cb6b8',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Visual/UI design',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '86a0de58-8613-4a54-d597-bf9e6f6f54b3',
    'vocabulary_machine_name' => 'service',
  );
  $terms[] = array(
    'name' => 'eActivism',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '87ce81af-2176-1074-31ba-ba31f478c13a',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Planning & Development',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8934912f-9e57-3ed4-41c9-5b766f46b4a2',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Administration',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '89556980-b4d7-3234-519c-655245331f79',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Firefox',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '89687c98-da19-64a4-39de-29775831116d',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Online Forums',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '89a8d555-dcea-6484-5db4-5c6632fde996',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Technical development',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '8b4b13e0-de22-b604-0583-fdaa5e00c6c2',
    'vocabulary_machine_name' => 'service',
  );
  $terms[] = array(
    'name' => 'Content Management System',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8cde29e4-d80c-d684-29a4-a05e177aa0e6',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'End user database',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8e4f5392-0cda-77c4-0109-c5bb54c198d8',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Water',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8f6dc846-f4d5-b4e4-79a1-6053a34afaac',
    'vocabulary_machine_name' => 'civic_category',
  );
  $terms[] = array(
    'name' => 'Online Chat',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '90800b21-74ca-1b64-750f-7ec657a57b03',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Flash',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '913fe16f-a0ba-11c4-49d1-c70c4aecd431',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Mobile',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '91dc0575-1800-4f14-419a-69f1cca0a5ee',
    'vocabulary_machine_name' => 'application_category',
  );
  $terms[] = array(
    'name' => 'Group Discounting',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '91ec0209-0403-6864-5972-6d5c3f4a9d13',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Open source',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '92d46be9-09bd-65f4-b1a4-310551bf066e',
    'vocabulary_machine_name' => 'software_type',
  );
  $terms[] = array(
    'name' => 'Housing',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9333a979-dcb9-ed04-dd48-145b04fc9e93',
    'vocabulary_machine_name' => 'civic_category',
  );
  $terms[] = array(
    'name' => 'eClinics',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '95080743-271b-5644-7df6-c20393f4b00a',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Software as a service',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '95b4aed1-baf1-efe4-25cd-ad90f9f21f71',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Effort Distributors',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9abf3c54-6bea-15e4-ad29-6a2c08054586',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Java',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9c06e931-8c3e-bc14-f96f-71ebbf1e1fd7',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Installation',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '9de5aac9-621a-88f4-e15d-b586cc1591ca',
    'vocabulary_machine_name' => 'service',
  );
  $terms[] = array(
    'name' => 'Comparators',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9e63a30a-1763-98f4-1506-58fab80a73e7',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Python',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9e6ba165-0f85-5a84-8503-4413276d5f48',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Crowdcasting',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a003d245-cc3e-28c4-496b-f4a9b7074649',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Courts & Justice',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a1d5f3c5-faaa-e004-e5fc-87f081867cba',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Joomla',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a272193e-e372-cc74-ed5f-8da814556124',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Health & Social Services',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a28893e7-c58a-cf94-f11f-e9540774ac73',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'eParticipatory Budgeting',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a5b87c27-a7c4-9874-2149-23ff0c7a967f',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Social Media',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'aa8541c9-80c8-8844-65f7-15846827b343',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Social Networking',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'aa990a46-6f55-6ba4-19c1-a5ee7b207fee',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Training',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => 'aafdb1b0-b017-6154-3dfa-fb4c9de0ffce',
    'vocabulary_machine_name' => 'service',
  );
  $terms[] = array(
    'name' => 'Technical support',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => 'ab022797-7c91-7cc4-c551-ef927b9bb285',
    'vocabulary_machine_name' => 'service',
  );
  $terms[] = array(
    'name' => 'Media Streaming',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'aca714eb-2e39-2f74-f1bd-6da936178cb2',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'PostGIS',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'af812e8a-7b51-7494-89af-acf95a7e4a4c',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Company',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '6',
    'uuid' => 'b14b498d-7185-a9e4-d5e0-eb88d3a0b76d',
    'vocabulary_machine_name' => 'organization_type',
  );
  $terms[] = array(
    'name' => 'Multilingual',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b3cab5de-e328-5e74-65f3-d21de66d779e',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Mapping',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => 'b49b12cc-efea-7614-91e5-632a860a549c',
    'vocabulary_machine_name' => 'application_category',
  );
  $terms[] = array(
    'name' => 'MySQL',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b4bdca4d-bbdd-eb34-8127-aecd910e789d',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Mapping',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b500103f-e817-2954-c595-e216369e9fda',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Multinational',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => 'b5a55738-3c40-aef4-0931-ed78e9fbabc0',
    'vocabulary_machine_name' => 'organization_type',
  );
  $terms[] = array(
    'name' => 'Instant Messaging',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b7bb3f6e-3c9c-6bd4-a922-570586dc25ac',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Social Reporting',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ba61f434-4044-2484-45bb-46d48deae6e9',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Libraries',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'bb21799c-24e3-7be4-c5a6-51b60f268d23',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Engagement',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'bf5d7d88-728f-9524-c11e-0c2a35d92c8b',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Finance',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c17d8eb0-4780-90d4-dda9-baf45bdacf3e',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Consumer Protection',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c1fc0fe6-0ffa-8384-fdef-0760ee0297a6',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Human Services',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c214b9dd-1ad2-be94-c9bd-142ccf84e8b5',
    'vocabulary_machine_name' => 'civic_category',
  );
  $terms[] = array(
    'name' => 'Windows',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c26f963a-13cb-55f4-65fe-86b02e63ba1a',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Research',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c388a07a-80d2-8a74-a1af-207323d59aac',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'PostgreSQL',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c425e455-708c-4084-456f-308ece4f3ee9',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Municipal',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '5',
    'uuid' => 'c4f32642-b538-6134-55b9-71c15944cec3',
    'vocabulary_machine_name' => 'organization_type',
  );
  $terms[] = array(
    'name' => 'Live Co-Creation',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c56bb9db-8cfd-d774-0907-54e02cb34cf0',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'ePetitions',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c5ba574e-ae78-c0d4-9965-d1870888b549',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Statistics',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c7e35ae7-70f5-8124-3d02-2627700f8abd',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Health',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c974fd94-0ab0-1424-0d23-9ef2fc6484f9',
    'vocabulary_machine_name' => 'civic_category',
  );
  $terms[] = array(
    'name' => 'Geography',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ccda9890-e0ff-fc94-45bd-19110e69eba9',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Risk Management',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ce7455ec-de53-7494-6de3-4b1df28cc721',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'CakePHP',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd111e098-2636-31b4-fd71-45b04fe15919',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'IE7',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd2e206bb-97b0-a174-31c4-5375d4991945',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'SOAP',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd33a9c18-52b2-1164-8128-6a82d39615e7',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'MIT',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => 'd42d1608-3038-37b4-d5f5-184f8efe5cf4',
    'vocabulary_machine_name' => 'license',
  );
  $terms[] = array(
    'name' => 'Drupal',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd57a99f3-5e83-7b84-358f-1ab68e5baf75',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Augmented Reality',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd58ebc31-f46c-eee4-f110-8d78fa5c8ffc',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Social Alerting',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd6c67eae-4dec-7934-9568-15bdec0efac5',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Education',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd894dbac-04d0-b1b4-bd50-f8cdce18c73d',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Accessibility',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd8c5bc09-a03f-0c74-3933-50fd03f8d773',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Safari',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd9d37603-6f1c-7ec4-cd3e-b24e4659a8d6',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Chrome',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'dd0130c8-741a-35d4-ad9c-da3ad8ef300b',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'MS Access',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ded05be0-b5fa-1674-f19c-df1317e900df',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Environment',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e1c64e63-1f7a-7bd4-b56f-928e66b711a8',
    'vocabulary_machine_name' => 'civic_category',
  );
  $terms[] = array(
    'name' => 'MongoDB',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e3efb117-8f82-4d84-9936-7d4081c6cbf4',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'ePanels',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e573ae04-2af6-0cc4-9dbd-58fcc51c74b1',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Business development',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => 'e63f62d7-df6c-41a4-750f-8e49924ae627',
    'vocabulary_machine_name' => 'service',
  );
  $terms[] = array(
    'name' => 'Education',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e8df941f-3ec8-46e4-0135-5eecf2605734',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Economic Development',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e99f6bbd-6138-2294-a920-2861a3e1f793',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Experience Sharing',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'eac18053-4992-5154-3de5-16f1e58e5bbc',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Networking by place',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'eb328dd7-756b-a4b4-310b-353406b206a6',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'git',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ebb8a19b-fcc7-3664-e52b-e773e46499da',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Accounting',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ec36fc92-0d24-fa64-f953-87e45c937dd4',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Ruby on Rails',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'eeedeb89-5fde-7934-2944-845cfba543a4',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'OpenStreetMap',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ef8c87d9-e757-8694-151e-5789e4443a10',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'Digital back channel',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ef9995a3-1de8-9604-a91b-90c95eb5b68d',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Resource Sharing',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f2382bc9-c7de-e1b4-895e-35a40bc27a62',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Online Survey',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f3fd287e-1458-82c4-e9ed-f3ace1977df8',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'BSD',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => 'f472ad8c-5935-be24-d187-2e99497fafee',
    'vocabulary_machine_name' => 'license',
  );
  $terms[] = array(
    'name' => 'Spatially Enhanced Consultation',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f5bf31cc-7073-9db4-01f0-536ce47373d1',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Debate or argument visualisation',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f62cd665-ad92-99d4-fd2e-db96b950213f',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Governance',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f6e42a9f-f4a0-c054-cdd4-c1ca7990ebfb',
    'vocabulary_machine_name' => 'civic_category',
  );
  $terms[] = array(
    'name' => 'Direct Democracy',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'faddd4b5-a6f7-8154-311a-cd1e4deee3cb',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Open Contest',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'fae091a7-8ef2-77f4-71ab-d405a7a467f0',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Taxes',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'fd077659-2a00-7e54-81fd-81c04b780df6',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'LAMP',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'fddd2ec4-4301-0194-2163-de0eb70e9275',
    'vocabulary_machine_name' => 'requirements',
  );
  $terms[] = array(
    'name' => 'IT Management',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'fe4e0c56-330b-1ba4-c98f-c71f30c3e5ef',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  $terms[] = array(
    'name' => 'Policy',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'fe5c5302-ae39-7ec4-ed40-665bcdfbab3d',
    'vocabulary_machine_name' => 'application_subcategory',
  );
  $terms[] = array(
    'name' => 'Data Harvesting',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'febd23ee-1edd-afb4-b522-2c094dd054a4',
    'vocabulary_machine_name' => 'civic_subcategory',
  );
  return $terms;
}
